// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQfQuhA6RCjBhSSK5D_-DT6LsMvnAXZ30',
    appId: '1:685785445423:web:cb15621d9a3981dac342da',
    messagingSenderId: '685785445423',
    projectId: 'my-todo-list-0668',
    authDomain: 'my-todo-list-0668.firebaseapp.com',
    storageBucket: 'my-todo-list-0668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5w9Vy8g8idafMH7ciQezC2WBncCZ9xU',
    appId: '1:685785445423:android:1501157728279c05c342da',
    messagingSenderId: '685785445423',
    projectId: 'my-todo-list-0668',
    storageBucket: 'my-todo-list-0668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Ik5RRe3KhPfRlnh_nGG7t1VGAj47N7g',
    appId: '1:685785445423:ios:60536434841e9d09c342da',
    messagingSenderId: '685785445423',
    projectId: 'my-todo-list-0668',
    storageBucket: 'my-todo-list-0668.appspot.com',
    iosClientId: '685785445423-ep41n5irg9kvabiu9svbuu2gnl3p66ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
